services:
      - docker

before_install:
      - docker build -t dockerseason -f Dockerfile.dev .

deploy:
  provider: elasticbeanstalk
  access_key_id:
    secure: $ACCESS_KEY_ID
  secret_access_key:
    secure: "$SECRET_ACCESS_KEY"
  region: "us-east-1"
  app: "docker-seasons"
  env: "Dockerseasons-env"
  bucket_name: "elasticbeanstalk-us-east-1-184329978736"
  bucket_path: "docker-seasons"
  on:
     branch: main